version: '2'

services:
  imap:
    # Uncomment this for build image in local
    # build:
    #   context: .
    image: antespi/docker-imap-devel:latest
    container_name: imap
    ports:
    - "25:25"
    - "143:143"
    - "993:993"
    environment:
    - MAILNAME=mail2.emotepaster.app
    - MAIL_ADDRESS=imap@emotepaster.app
    - MAIL_PASS=password1234
